from enum import Enum as PyEnum


class TipoNotificacion(str, PyEnum):
    RECORDATORIO = "RECORDATORIO"
    PAGO = "PAGO"
    PAGO_CONFIRMADO = "PAGO_CONFIRMADO"
    CAMBIO_HORARIO = "CAMBIO_HORARIO"
    CAMBIO_INSTRUCTOR = "CAMBIO_INSTRUCTOR"
    NUEVA_CLASE = "NUEVA_CLASE"
    CANCELACION = "CANCELACION"
    REEMBOLSO = "REEMBOLSO"
    BLOQUEO_CUENTA = "BLOQUEO_CUENTA"
    RESERVA_CONFIRMADA = "RESERVA_CONFIRMADA"
    RESERVA_CANCELADA = "RESERVA_CANCELADA"
    CAMBIO_ESPACIO = "CAMBIO_ESPACIO"
    NOTIFICACION_GENERAL = "NOTIFICACION_GENERAL"


class RespuestaNotificacion(str, PyEnum):
    ACEPTADO = "ACEPTADO"
    CANCELADO = "CANCELADO"
